Repository DmitryKolotilshikov/fe32-js-module-1, pull requests merged in 2022-07, with the labels that each got.

#54 added hw-3
  js/hw-3.js
  js/hw-4.js
Labels: Approved (with fix)

#47 Anna hw3
  HW1.md
  README.md
  index.html
  js/anna-hw3.js
Labels: Approved (with fix)

#25 init(hw_2):my second HW
  hw_2.js
Labels: Approved (with fix)

#48 Dmitriynsvhw3
  HW2.md
  HW3.md
  README.md
  hw3.js
  js/2_states_cycles.js
Labels: Approved (with fix)

#51 vera-hw_3
  HW1.md
  HW2.md
  index.html
  js/1_data_types.js
  js/vera-hw_3.js
Labels: Approved

#52 add HW3.js
  JS/HW3.js
  index.html
Labels: Approved (with fix)

#34 пытаюсь залить в свою ветку hw-2
  HW-3/hw3.js
  HW-3/index.html
  HomeWork-2/hw-2.js
  HomeWork-2/index.html
  hw-4/hw4.js
  hw-4/index.html
Labels: Approved (with fix)

#57 E.kireev hw4
  index.html
  js/hw-4.js
Labels: Approved

#63 A.cherkas hw 4
  index.html
  js/hw4.js
Labels: Approved

#73 A.cherkas hw 5
  index.html
  js/hw5.js
Labels: Approved

#61 added hw-4
  js/hw-4.js
Labels: Approved

#70 kostya-zayats hw4
  index.html
  script/hw_4.js
Labels: Approved

#71 Darya.yaskevich.hw3+hw4
  HW1.md
  alert.js
  hw_1.js
  hw_2.js
  hw_3.js
  hw_4.js
  index.html
  wb.js
Labels: Approved

#79 o.grishchenko_hw-5
  js/hw-5.js
Labels: Approved (with fix)

#87 A.cherkas hw 6
  index.html
  js/hw6.js
Labels: Approved (with fix)

#75 L.Zhukovets hw4.js
  JS/HW3.js
  JS/hw4.js
  index.html
Labels: Approved (with fix)

#91 Leonid.z hw6
  JS/hw6.js
  index.html
Labels: Approved

#108 add hw-7
  js/HW-1.js
  js/hw-2.js
  js/hw-3.js
  js/hw-4.js
  js/hw-7.js
Labels: Ready for review

#81 hw5
  hw4.js
  index.html
Labels: Approved

#110 Alexandra hw4
  HomeWork-2/hw-2.js
  hw-4/hw4.js
Labels: Approved

#101 A.cherkas hw 7
  index.html
  js/hw7.js
Labels: Approved

#100 add hw7.js
  JS/hw7.js
  index.html
Labels: Approved

#104 o.grishchenko added hw-7
  js/hw-7.js
Labels: Approved

#62 Anna hw4 (functions)
  index.html
  js/anna-hw4.js
Labels: Approved

#78 Anna hw5 / Objects
  index.html
  js/anna-hw5.js
Labels: Approved

#93 Anna hw6/ Arrays
  index.html
  js/anna-hw6.js
Labels: Approved

#102 Anna hw7/ Methods of Arrays
  index.html
  js/anna-hw7.js
Labels: Approved

#109 E.kireev hw 7
  js/HW-1.js
  js/hw-2.js
  js/hw-3.js
  js/hw-4.js
  js/hw-7-fix.js
Labels: Approved

#72 Ivan.filipenko hw2+hw3
  hw2/ivan-hw2.js
  hw3/ivan-hw3.js
Labels: Approved

#89 Saveliy.shovgur hw6
  hw6.js
  index.html
Labels: Approved

#88 Dmitriynsv hw5
  HW2.md
  HW3.md
  HW4.md
  HW5.md
  js/4.1_hoisting.js
  js/4.2_script_hw4_tasks.js
  js/4_functions.js
  js/5_objects.js
  js/hw5.js
Labels: Approved
