Repository DmitryKolotilshikov/fe32-js-module-1, pull requests merged in 2022-06, with the labels that each got.

#11 added leonid-hw1.js
  JS/leonid-hw1.js
Labels: ready for review

#14 My first pull request
  hw_1.js
Labels: Ready for review

#15 комментариий
  hw_1.js
Labels: Ready for review

#17 added ivan-hw1.js
  index.html
  ivan-hw1.js
Labels: Ready for review

#16 My first pull request
  hw_1.js
Labels: Ready for review

#18 Yauheni hw 1
  JS/Yauheni-hw1.js
Labels: Ready for review

#26 My first pull request
  hw_1.js
Labels: Approved

#27 A.cherkas_hw_2
  index.html
  js/hw2.js
Labels: Approved (with fix)

#28 E.kireev hw 2
  .gitignore
  HW1.md
  index.html
  js/hw-2.js
Labels: Approved (with fix), Approved

#37 Kostya Zayats hw2
  HW2.md
  README.md
  index.html
  js/1_data_types.js
  script/hw_1.js
  script/hw_2.js
Labels: Approved

#36 Katya_hw1
  index.html
  js/hw_1.js
Labels: Approved

#33 added all task from HW-2
  .DS_Store
  HW2/app.js
  HW2/index.html
Labels: Approved

#22 Name.nsvhw2
  HW2.md
  README.md
  js/1_data_types.js
  js/hw2.js
Labels: Approved (with fix)

#29 init:created hw-2.js
  js/hw-2.js
Labels: Approved (with fix)

#32 Anna Rubchenia / added HW2
  index.html
  js/anna-hw2.js
Labels: Approved (with fix)

#44 Darya.yaskevich hw2
  alert.js
  hw_2.js
  index.html
Labels: Approved (with fix)

#42 Added all tasks from hw-3 list.
  HW2/app.js
  HW3/index.html
  HW3/scripts/hw3.js
Labels: Approved (with fix)

#45 added hw-3
  index.html
  js/hw-3.js
Labels: Approved

#46 A.cherkas_hw_3
  index.html
  js/hw3.js
Labels: Approved (with fix)

#55 HomeWork-3
  index.html
  js/js-hw3/app-hw3.js
Labels: Approved
